export const ActionTypes = {
    //Auth Actions
    REGISTER_USER: 'REGISTER_USER',
    FETCH_USER_DETAIL: 'FETCH_USER_DETAIL',
    DELETE_USER: 'DELETE_USER',
    UPDATE_USER: 'UPDATE_USER',
    REQUEST_PASSWORD_RESET: 'REQUEST_PASSWORD_RESET',
    FINISH_PASSWORD_RESET: 'FINISH_PASSWORD_RESET',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    ACTIVATE_USER: 'ACTIVATE_USER',


    // status actions
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
}